# Software tools

You should draft your thesis in RStudio using the bookdown package (which was also used to produce this document). This will allow you to generate a PDF document in addition to an HTML-based ebook that can include interactive elements. @xie2016bookdown includes full documentation for the bookdown package, and you can access it freely online [here](https://bookdown.org/yihui/bookdown/){target="_blank"}.

You should maintain all code used to produce your thesis (both the document and any analysis) in a GitHub repository. I will offer feedback and suggest edits using GitHub issues and pull requests.

To set up your thesis as a bookdown document within a GitHub repository, take the following steps:

1. Create a new RStudio project by selecting "New project" from the File menu in RStudio, then "New Directory", the "Book project using bookdown." Name your project directory something descriptive that pertains to your thesis topic (i.e. do not name it "thesis").
2. Install the `usethis` package, if it isn't already installed, then type `usethis::use_git()` in your RStudio console. Next, type `usethis::use_github()` in your console. This will create a local Git repository and an associated GitHub repository from your RStudio project.
3. Open the file _bookdown.yml and add a line that says `output_dir: "docs"` at the end.
4. In the Build tab of RStudio, click "Build Book."
5. Go the the Git tab of RStudio. Stage, Commit, and Push your changes.
6. Navigate to your GitHub repo on your web browser. Go to settings, then select "Pages" from the left sidebar. Under the "Source" heading, set the Branch as "main" and the folder as "/docs". Then click Save.

You may find it very useful to use Zotero to manage your citations. One of the biggest advantages of citation management software (like Zotero) is that it automatically generates formatted citations for you and lets you easily convert between citation formats in Microsoft Word or Google Docs. Bookdown has this functionality as well, so I won't insist on your using Zotero, but you might still choose to. For a Bookdown document, you'll keep a running list of your references in a file called book.bib. You'll use a format called BibTex for this. You can generate BibTeX citations to paste into the book.bib file in one of two ways:

1. Search for the source in Google Scholar. Click on the "Cite" link under the entry for your source, and a window will appear with bibliographic entries in MLA, APA, Chicago, Harvard, and Vancouver formats. At the bottom of that window, click on the link that says "BibTeX". A block of BibTeX text will appear in your browser. Copy and paste that text to the book.bib file in your bookdown project directory.

2. Save all your thesis sources to a folder in your Zotero library. Open Zotero and right-click on the folder where all your thesis sources are saved. Select "Export collection." In the "Export..." window that appears, select "BibTeX" as the format. Save the resulting file as book.bib in your bookdown project directory (overwriting the existing book.bib file).
