# Key dates

This section describes tasks you should complete as part of your thesis work with me and the approximate dates by which you should complete them.

## Summer before thesis year

### Reading to prepare you for writing

During the summer before your thesis year, you should read the following books:

_How to Fix Your Academic Writing Trouble_ [@mewburn2018ebook]. This is a very good introduction to academic writing. Even if you are a very good writer with extensive academic writing experience, I would like you to read this entire book so that we'll have a common foundation on which to build when I give you feedback on your writing.

_Bookdown: authoring books and technical documents with R markdown_ [@xie2016bookdown], This is a reference on how to use the bookdown package. You can read it for free [here](https://bookdown.org/yihui/bookdown/){target="_blank"}. You do not need to read it cover to cover, but I want you to look through it so that you're well prepared to use it as a reference.

### Setting up a GitHub repository

Over the summer, use the template I will provide you to set up a GitHub repository for your thesis. Name the repository something that describes your topic (i.e. don't call it "Thesis"). Add me to your repository as a collaborator.

### Tasks specific to your research topic

There are two project-specific tasks you should complete during the summer before your thesis year:

#### Define your research question

Prior to our first meeting in the fall, you should develop a specific question you would like to answer through your research. You will have time to refine this question in the thesis prep course. You may find Chapter Three of The Craft of Research [@booth_chapter_2016] to useful in thnking about what makes a useful research question.

#### Assemble some inital sources

Find at least five journal articles that are relevant to the research question you've identified and add them to the book.bib file in your thesis GitHub repository.

## Fall of your thesis year

Over the course of fall semester, you will develop a thesis proposal as part of the thesis prep course. Much of the material you write for your thesis proposal can be incorporated into your thesis. You should add that material to the thesis draft in your GitHub repository as you go along. 

### Methods chapter

Before the start of Spring semester, you should write a complete draft of the the **methods chapter** of your thesis and complete any necessary IRB applications.

## Spring of your thesis year

In general, you should give me at least one week to review each chapter of your thesis. 

### Results chapter

Submit a draft of the results chapter to me **at least one week before the Spring semester midterm review** (about ten weeks before the final thesis review).

### Discussion chapter

Submit a draft of the discussion chapter to me at least eight weeks before the final thesis review.

### Literature review chapter

Submit a draft of the literatire review chapter to me at least six weeks before the final thesis review.

### Conclusion chapter

Submit a conclusion chapter to me at least four weeks before the final thesis review.

### Introduction chapter

Submit an introduction chapter to me at least two weeks before the final thesis review.

### Complete draft

Submit a complete draft to me at least one week before the final thesis review.
